FROM python:3.10 as base

COPY . /app

WORKDIR /app

RUN pip install --upgrade pip

RUN pip install --no-cache -r requirements.txt

FROM base as final

COPY --from=base app app

WORKDIR /app

ENTRYPOINT [ "python" ]

CMD ["main.py" ]