FROM python:3.10 as builder

COPY . /app

WORKDIR /app

RUN pip install --upgrade pip

RUN pip install --no-cache -r requirements.txt

FROM builder as final

COPY --from=builder app app

WORKDIR /app

ENTRYPOINT [ "python" ]

CMD ["main.py" ]